name: Build and Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows]
        goarch: [amd64]
        include:
          - goos: linux
            ext: ""
          - goos: windows
            ext: ".exe"
    env:
      GOOS: ${{ matrix.goos }}
      GOARCH: ${{ matrix.goarch }}
      CGO_ENABLED: 0

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20.x'
        check-latest: true

    - name: Build
      run: |
        OUTPUT="envctl-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.ext }}"
        go build -ldflags="-s -w" -o bin/$OUTPUT ./cmd/envctl
        echo "BUILD_VERSION=$(git describe --tags --always)" >> $GITHUB_ENV

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: envctl-binaries
        path: bin/
        retention-days: 3

  release:
    name: Create Release
    needs: [build]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        name: envctl-binaries
        path: release-binaries

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          release-binaries/*
        body: |
          Automated build of envctl
          - Commit: ${{ github.sha }}
          - Version: ${{ env.BUILD_VERSION }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
